### ISSUE TITLE
如何搭建前端测试环境【热度: 505】

### ISSUE THREAD

**Issue by yanlele** [pro-collection/interview-question#1099]
**关键词**：前端测试

搭建前端测试体系是一个系统性工程，下面从几个关键方面详细介绍其搭建步骤：

### 1. 规划测试策略

- **确定测试范围**：明确需要测试的前端项目部分，例如页面布局、交互功能、组件、API 调用等。要考虑项目的规模、复杂度以及业务的关键功能点。
- **设定测试目标**：比如保证代码质量、提升用户体验、减少线上故障等。不同的目标会影响测试的深度和广度。
- **制定测试计划**：规划测试的阶段、时间节点、参与人员等。例如，在开发的不同阶段安排不同类型的测试，如单元测试在开发过程中同步进行，集成测试在模块合并后开展等。

#### 单元测试

- **Jest**：功能强大且易于上手，有丰富的断言库和模拟功能，自带测试运行器，能自动并行执行测试用例，广泛应用于 React、Vue 等项目。
- **Mocha**：灵活度高，可搭配不同的断言库（如 Chai）和模拟库（如 Sinon）使用，支持异步测试，适用于各种 JavaScript 项目。

#### 集成测试

- **React Testing Library**：专注于从用户交互角度测试 React 组件，鼓励编写接近用户使用场景的测试用例。
- **Vue Test Utils**：是 Vue.js 官方提供的测试工具，能方便地挂载和测试 Vue 组件，处理组件间的交互。

#### 端到端（E2E）测试

- **Cypress**：具有实时重新加载、自动等待等特性，能直观展示测试运行过程，易于调试，适合各种前端项目，尤其是单页面应用。
- **Puppeteer**：基于 Chrome 或 Chromium 浏览器，可模拟复杂的用户操作，如页面滚动、文件上传等，常用于性能测试和自动化操作。

#### 单元测试用例

针对单个函数、组件或模块编写测试用例，确保其功能的正确性。例如，对于一个计算两个数之和的函数，可以编写以下测试用例：

```javascript
function sum(a, b) {
  return a + b;
}

test("adds 1 + 2 to equal 3", () => {
  expect(sum(1, 2)).toBe(3);
});
```

#### 集成测试用例

测试多个组件或模块之间的交互是否正常。例如，测试一个表单组件与数据提交逻辑的集成：

```javascript
import React from "react";
import { render, fireEvent } from "@testing-library/react";
import Form from "./Form";

test("form submits data correctly", () => {
  const mockSubmit = jest.fn();
  const { getByLabelText, getByText } = render(<Form onSubmit={mockSubmit} />);
  const input = getByLabelText("Name");
  const submitButton = getByText("Submit");

  fireEvent.change(input, { target: { value: "John" } });
  fireEvent.click(submitButton);

  expect(mockSubmit).toHaveBeenCalledWith({ name: "John" });
});
```

#### 端到端测试用例

模拟用户在浏览器中的真实操作流程，确保整个应用的功能正常。例如，使用 Cypress 测试一个登录页面：

```javascript
describe("Login page", () => {
  it("logs in successfully", () => {
    cy.visit("/login");
    cy.get('input[name="username"]').type("testuser");
    cy.get('input[name="password"]').type("testpassword");
    cy.get('button[type="submit"]').click();
    cy.url().should("include", "/dashboard");
  });
});
```

### 4. 集成持续集成/持续部署（CI/CD）

将测试集成到 CI/CD 流程中，每次代码提交或合并时自动触发测试。常见的 CI/CD 工具有 Jenkins、GitLab CI/CD 和 GitHub Actions。以下是一个使用 GitHub Actions 运行 Jest 单元测试的示例配置文件：

```yaml
name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
```

### 5. 代码覆盖率检测

使用工具如 Istanbul（Jest 内置支持）检测代码的测试覆盖率，确保测试覆盖到尽可能多的代码。可以在 CI/CD 流程中设置代码覆盖率阈值，若不达标则阻止代码部署。例如，在 Jest 配置中设置覆盖率阈值：

```json
{
  "coverageThreshold": {
    "global": {
      "branches": 80,
      "functions": 80,
      "lines": 80,
      "statements": 80
    }
  }
}
```

### 6. 性能测试和监控

使用工具如 Lighthouse、WebPageTest 对前端应用的性能进行测试，包括页面加载时间、响应时间等指标。根据测试结果对代码和资源进行优化。同时，建立性能监控系统，持续跟踪应用的性能变化。

### 7. 维护和优化测试体系

随着项目的发展，不断维护和更新测试用例，确保测试的有效性和准确性。定期审查测试体系，根据项目需求和技术发展进行调整和优化。例如，引入新的测试框架或工具，改进测试用例的编写方式等。
