### ISSUE TITLE
介绍一下 position sticky【热度: 826】

### ISSUE THREAD

**Issue by yanlele** [pro-collection/interview-question#884]
**关键词**：position sticky

`position: sticky;` 是 CSS 中的一个定位属性值，它允许元素在页面滚动到某个阈值时“固定”在位置上，而在达到这个阈值之前，元素会像正常文档流中的元素一样表现（也就是说，在特定条件下它表现得像 `position: relative;`，在另一些条件下表现得像 `position: fixed;`）。这种特性使 `sticky` 定位成为实现网页上吸顶或吸底效果的一种非常实用的手段。

### 特性

- **吸顶效果**：最常见的用途之一是导航栏吸顶。当用户向下滚动页面时，导航栏到达视口顶部后就会固定在那里，直到用户向上滚动至原始位置。
- **滚动容器**：`sticky` 元素将相对于离其最近的拥有滚动机制（例如，`overflow: auto;` 或 `overflow: scroll;`）的祖先元素进行定位。

### 如何使用

要使元素具有 `sticky` 定位，你需要为它指定 `position: sticky;` 以及至少一个“边缘”属性（`top`, `right`, `bottom`, `left`）的值。这个值决定了元素在满足“粘性”条件前与边缘的距离。

### 示例

```css
.sticky-element {
  position: -webkit-sticky; /* Safari */
  position: sticky;
  top: 0; /* 距离顶部 0px 时生效 */
  z-index: 1000; /* 确保在其他内容之上 */
  background-color: white; /* 可选：为了视觉效果更明显 */
}

.container {
  overflow-y: auto; /* 确保是滚动容器 */
  height: 500px; /* 举例，根据实际需求设置 */
}
```

```html
<div class="container">
  <div class="sticky-element">我在滚动时会吸顶</div>
  <!-- 其他内容 -->
</div>
```

### 注意事项

- **兼容性**：`position: sticky;` 在大多数现代浏览器上都得到了支持，但在一些旧版浏览器中可能需要使用前缀或不被支持。
- **父元素的 `overflow`**: 如果一个元素的任何父元素具有 `overflow: hidden`、`overflow: scroll` 或 `overflow: auto` 样式，则 `position: sticky` 可能不会生效。
- **祖先的 `display`**: 某些 `display` 值（如 `display: table-cell` 等）也可能影响 `position: sticky` 的行为。
- **使用时机**：虽然 `sticky` 提供了一种便捷的方式来实现吸附效果，但在一些复杂的布局中，可能需要额外的样式调整或脚本支持来达到预期的效果。

通过灵活运用 `position: sticky;`，可以在无需 JavaScript 的情况下，实现许多响应用户滚动的交互效果。
